### ISSUE TITLE
Julich Brain 3.0 and 3.1 (prerelease) have some PMAPs that are not masked with the templates

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-configurations#4]
as of 0.4a63

sample code:

```python
import siibra

pt_spec = siibra.Point.parse("18.505544mm,-1.754904mm,33.293708mm")
pt = siibra.Point(pt_spec, space=siibra.spaces['mni152'])
statmap = siibra.get_map("3.0.3", "mni152", "statistical")
df = statmap.assign(pt)
print(len(df)) # expects 0, got 1
print(df['region']) # expects None, got `Ventral Dentate Nucleus (Cerebellum) right`
```

[atlas location](https://atlases.ebrains.eu/viewer/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2/p:minds:core:parcellationatlas:v1.0.0:94c1125b-b87e-45e4-901c-00daee7f2579-300/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIy..16bz8.6iSO~.1-0MC..1LSm) clearly does not point to any region

related https://github.com/FZJ-INM1-BDA/siibra-explorer/issues/1401

**Comment by dickscheid** [comment]
I agree it should be solved on the data side. Using a default threshold is difficult, since the interpretation of values is different for different maps (e.g. difumo vs. julich-brain). Of course it should be possible to use a threshold, but it needs to be explicit, not implicit then. If no threshold is given, which should be the default in my eyes, the dataset (parcellation map) defines which regions are assigned with its nonzero values. Of course, the given example is anything else than intuitive and should be clarified.

**Comment by AhmetNSimsek** [comment]
I've just talked with Hartmut who confirmed it is an error. He will check his original data and contact us.

**Comment by AhmetNSimsek** [comment]
> I've just talked with Hartmut who confirmed it is an error. He will check his original data and contact us.

Hartmut said it is indeed a data issue at the source. This will be remedied for Julich Brain 3.1.
